-- this will match what papa parse generates (and mysql timestamp formats to snowflake)
CREATE FILE FORMAT "DATABASE"."SCHEMA".CSV_WITH_HEADER_ENCLOSING_DOUBLE 
  COMPRESSION = 'AUTO'
  FIELD_DELIMITER = ','
  RECORD_DELIMITER = '\n'
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '\042'
  TRIM_SPACE = FALSE
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
  ESCAPE = 'NONE'
  ESCAPE_UNENCLOSED_FIELD = '\134'
  DATE_FORMAT = 'AUTO'
  TIMESTAMP_FORMAT = 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"'
  NULL_IF = ('\\N');
-- Allow snowpipe to use this format (put in the role that you are using)
GRANT USAGE ON FILE FORMAT DATABASE.SCHEMA.CSV_WITH_HEADER_ENCLOSING_DOUBLE
TO ROLE SNOWPIPE_DATA_LOADER;